- lib/lhc/endpoint.rb
- lib/lhc/request.rb
- spec/config/endpoints_spec.rb
Bug: Configured endpoints with default params can just be called once. After that the endpoints options are empty.
Reason: Endpoints options should not be mutated. I made them immutable in order to ensure this.
> Fix configured default params

- README.md
- lib/lhc.rb
- lib/lhc/concerns/lhc/formats.rb
- lib/lhc/formats/json.rb
- lib/lhc/response.rb
- spec/basic_methods/get_spec.rb
Shortcut should
- Request JSON
- Parse json when `.data` is requested
Solves: https://github.com/local-ch/lhc/issues/15
> Allow json shortcut methods

- lib/lhc/request.rb
- lib/lhc/response.rb
- spec/response/effective_url_spec.rb
- enables the option `follow_location`
- enables the method `effective_url` for responses
Both allows you to follow redirects and access the effective url in the end.
As request here https://github.com/local-ch/lhc/issues/38
> enable follow redirect and effective url

- lib/lhc/request.rb
- spec/request/url_patterns_spec.rb
The request body was not considered when trying to compile url patterns "datastore/v2/places/:id".
It was not considering data from the body to construct those urls.
> ! consider body when compiling/generating urls

- .rubocop.yml
- lib/lhc/endpoint.rb
- non_rails_spec/request/request_spec.rb
- spec/endpoint/match_spec.rb
- spec/request/error_handling_spec.rb
The endpoint matcher was broken/incomplete
This method is used to check if a certain url matches a certain url template
```
:datastore/v2/places/:id == http://local.ch/v2/places/123
:datastore/v2/places/:id != http://local.ch/v2/places
etc.
```
> ! endpoint matching

- lib/lhc/endpoint.rb
- spec/endpoint/compile_spec.rb
- spec/endpoint/match_spec.rb
Fixes https://github.com/local-ch/lhc/issues/53
Fixes endpoint detection with dots, a regression from the previous regexp optimizations for url-templates.
```ruby
LHC.config.placeholder(:devices, ':datastore/devices/:device_id.json')
LHC.get(:devices, params: { device_id: device_id })
```
Now the : (column) indicated variables don't include `dots` anymore.
Also evaluated to switch to the [rfc6570](https://tools.ietf.org/html/rfc6570) but it excludes uri scheme from templating, so stuff like `:datastore/v2/place/:id` would stop working, what I would find quite inconvenient right now.
> ! fix endpoint detection with dots

- README.md
- lib/lhc/request.rb
- lib/lhc/response.rb
- spec/request/error_handling_spec.rb
- spec/request/headers_spec.rb
You can provide custom error handlers to handle errors happening during the request.
If a error handler is provided nothing is raised.
If your error handler returns anything else but `nil` it replaces the response body.
```ruby
handler = ->{ do_something; return {name: 'unknown'} }
response = LHC.get('http://something', error_handler: handler)
response.data.name # 'unknown'
```
---------
- Required for some LHS feature to chain error handling and inject data in case of errors
- Minor version increase ahead
> Request error handlers

- README.md
- lib/lhc/formats/json.rb
- lib/lhc/response.rb
- lib/lhc/response/data.rb
- lib/lhc/version.rb
- spec/response/data_spec.rb
Minor version increase
The response data can be access with dot-notation and square-bracket notation. You can convert response data to open structs or json (if the response format is json).
```ruby
response = LHC.request(url: 'http://datastore/entry/1')
response.data.as_open_struct #<OpenStruct name='local.ch'>
response.data.as_json # { name: 'local.ch' }
response.data.name # 'local.ch'
response.data[:name] # 'local.ch'
```
> + improve accessing response data

- README.md
- lib/lhc/response.rb
- spec/response/data_accessor_spec.rb
Minor version
You can also access response data directly through the response object (with square bracket notation only):
```ruby
LHC.json.get(url: 'http://datastore/entry/1')[:name]
```
This makes accessing the data object with `.data` unnecessary and direct data retrieval a little more convenient.
> Access data directly on response

- lib/lhc.rb
- lib/lhc/test/cache_helper.rb
*PATCH* 
Apps in production that dont have rspec gem were raising exceptions because this file was not testing if rspec is arround.
> ! dont configure rspec when its not arround

- docs/interceptors/caching.md
- lib/lhc/interceptors/caching.rb
- spec/interceptors/caching/main_spec.rb
- spec/interceptors/caching/methods_spec.rb
*Major Version: As finally sets GET as the only HTTP method cached by default, when enabling the caching interceptor*
[...]
Only GET requests are cached by default. If you want to cache any other request method, just configure it:
```ruby
LHC.get('http://local.ch', cache: true, cached_methods: [:post, :head])
```
> [Caching Interceptor] Improve cached methods

- lib/lhc/interceptors/caching.rb
- lib/lhc/response.rb
- spec/interceptors/caching/main_spec.rb
- spec/interceptors/caching/methods_spec.rb
*PATCH*
Because typhoeus relies on `mock` internal when determining `success?` https://github.com/typhoeus/typhoeus/blob/181834e2483d392d0f7ab0cd17f544cd252c7b2f/lib/typhoeus/response/status.rb#L49 I was faced with some failing responses served from cache.
Adding mock to the data stored and restored from cache, solved that problem.
> Add mock to cached response data

- .gitignore
- lib/lhc/concerns/lhc/basic_methods.rb
- spec/interceptors/caching/hydra_spec.rb
*PATCH*
Requests served from cache have been performed nevertheless when done in parallel with hydra.
> [FIX] Dont do requests when done with hydra but served from cache

- lib/lhc/endpoint.rb
- spec/endpoint/match_spec.rb
*Patch Version*
Some hyperlinks already contain get parameters, reflecting default parameter/values, for example offset & limit:
```
GET http://datastore/places/1
{
feedbacks: { href: 'http://datastore/places/1/feedbacks?limit=10&offset=0' }
}
```
Those have not been matched by url templates like `:datastore/places/:id/feedbacks`.
Now they are.
> ! consider url params when matching url templates

- lib/lhc/response.rb
*PATCH*
LHC version 5.1.0 broke latest LHS and I don't know for which reasons. Maybe an implicit patch/minor version upgrade of `active_support` triggered that:
```
`<class:Response>': undefined method `delegate' for LHC::Response:Class (NoMethodError) Did you mean? DelegateClass
```
> ! fix delegate by requiring active support ext explicit

- lib/lhc/errors/client_error.rb
- lib/lhc/errors/parser_error.rb
- lib/lhc/errors/server_error.rb
- lib/lhc/errors/timeout.rb
- lib/lhc/errors/unknown_error.rb
*PATCH*
Those requires are not required anymore, due to the ruby autoload implementation.
> Remove some autoload leftovers

- lib/lhc/interceptors/caching.rb
- lib/lhc/response.rb
- spec/interceptors/caching/main_spec.rb
*Minor*
Fixes https://github.com/local-ch/lhc/issues/86
> When using the monitoring interceptor on an LHC instance that also uses the Caching interceptor you may get a skewed picture, because the monitoring interceptor has no way of knowing whether the request was served by the cache or not.
> Mark responses served from from cache as from cache

- lib/lhc/endpoint.rb
- spec/endpoint/placeholders_spec.rb
*PATCH*
LHC failed parsing urls like `https://d123token:@api.github.com/search`. 
As you would find them when communicating with Github Api.
LHC tried to find the `:@api` placeholder in this case.
Ignore `@` when it comes to detect placeholders.
> Fix basic auth in url

- lib/lhc/endpoint.rb
- spec/endpoint/placeholders_spec.rb
_PATCH_
LHC was not compiling urls when they contained complete basic auth informations `user:password@`.
Now it does, by stripping the auth infos from the url string when compiling, and adding them after compilation happened.
> FIX urls with basic auth

- lib/lhc.rb
- lib/lhc/request.rb
- lib/lhc/response.rb
After the incidents we had with content_pages, lets require typhoeus for whole lhc.
https://rollbar.com/local.ch/content-pages/items/45/
> ! require 'typhoeus' for whole lhc

- README.md
- lib/lhc/request.rb
- lib/lhc/response.rb
- spec/request/ignore_errors_spec.rb
_MINOR_
As it's discouraged to rescue errors and then don't handle them (ruby styleguide),
but you often want to continue working with `nil`, LHC provides the `ignore_errors` option.
Errors listed in this option will not be raised and will leave the `response.body` and `response.data` to stay `nil`.
```ruby
response = LHC.get('http://something', ignored_errors: [LHC::NotFound])
response.body # nil
response.data # nil
```
> Ignore certain errors

- lib/lhc/request.rb
- spec/request/ignore_errors_spec.rb
_PATCH_
LHC `ignored_errors` has not been taken in consideration inheritance of errors.
```ruby
LHC.get('http://local.ch', ignored_errors: [LHC::Error])
```
```ruby
```
> Take in considarition error inheritance

- README.md
- lib/lhc/request.rb
- lib/lhc/response.rb
- spec/request/ignore_errors_spec.rb
_MINOR_
Makes `error_ignored?` available on response and request.
As it's discouraged to rescue errors and then don't handle them (ruby styleguide),
but you often want to continue working with `nil`, LHC provides the `ignored_errors` option.
Errors listed in this option will not be raised and will leave the `response.body` and `response.data` to stay `nil`.
```ruby
response = LHC.get('http://something', ignored_errors: [LHC::NotFound])
response.body # nil
response.data # nil
response.error_ignored? # true
response.request.error_ignored? # true
```
> Make ignore errors available

- README.md
- docs/interceptors/prometheus.md
- lhc.gemspec
- lib/lhc.rb
- lib/lhc/interceptors/prometheus.rb
- lib/lhc/response.rb
- spec/interceptors/prometheus_spec.rb
- spec/response/time_spec.rb
_MINOR_
Logs basic request/response information to prometheus.
```ruby
require 'prometheus/client'
LHC::Prometheus.client = Prometheus::Client
LHC::Prometheus.namespace = 'web_location_app'
LHC.config.interceptors = [LHC::Prometheus]
```
```ruby
LHC.get('http://local.ch')
```
- Creates a promethues counter that receives additional meta information for: `:code`, `:success` and `:timeout`.
- Creates a promethues histogram for response times in milliseconds.
> Prometheus interceptor

- .rubocop.yml
- README.md
- docs/interceptors/retry.md
- lib/lhc.rb
- lib/lhc/interceptors/retry.rb
- lib/lhc/request.rb
- lib/lhc/version.rb
- spec/interceptors/retry/main_spec.rb
- spec/request/parallel_requests_spec.rb
_MINOR_
Mainly needed for Uberall (my presence sync) right now ;(
If you enable the retry interceptor, you can have lhc retry requests for you:
```ruby
LHC.config.interceptors = [LHC::Retry]
response = LHC.get('http://local.ch', retry: true)
```
It will try to retry the request up to 3 times (default) internally, before it passes the last response back, or raises an error for the last response.
Consider, that all other interceptors will run for every single retry.
```ruby
LHC.get('http://local.ch', retry: { max: 1 })
```
```ruby
LHC::Retry.max = 3
```
> Retry interceptor

- lib/lhc/endpoint.rb
- lib/lhc/version.rb
Missing a `require 'uri'` in endpoint file.
> Fix missing URI require

- README.md
- lhc.gemspec
- lib/lhc/request.rb
- lib/lhc/version.rb
- spec/request/params_encoding_spec.rb
Allows to use the option `params_encoding` to encode array parameters in different ways for APIs.
> Enable params_encoding option

- lib/lhc/interceptor.rb
- lib/lhc/version.rb
- spec/interceptors/dup_spec.rb
In some applications, mainly Salesbutler, we have the problem that the whole log is flooded with:
```
[WARNING] Can't enable LHS::RequestCycleCache as LHC::Caching interceptor is not enabled/configured (see https://github.com/local-ch/lhc/blob/master/docs/interceptors/caching.md#caching-interceptor)!
```
While this warning is actually accurate, the RequestCycleCache is partially not active, which means we loose the benefit of caching the same requests during one request cycle!
The reason why the request cycle cache is partially not working, in this scenario, is the following:
1. Application makes request using LHS includes:
https://github.com/local-ch/sales-butler/blob/master/app/models/customer.rb#L139
2. LHS includes (auto-loads) additional linked resources: …
> DO NOT dup interceptors

- docs/interceptors/default_timeout.md
- lib/lhc/interceptors/default_timeout.rb
- lib/lhc/version.rb
- spec/interceptors/default_timeout/main_spec.rb
In one of our applications (salesbutler) we had a lot of problems with a default connecttimeout of 1 second. After running a test with 2 seconds, it seems to be the way better default for our infrastructure.
> New default connect timeout

- lib/lhc.rb
- lib/lhc/version.rb
- spec/basic_methods/request_without_rails_spec.rb
quick fix for missing `deep_symbolize_keys` in apps that do not operate under rails
> add require for deep_symbolize_keys

- README.md
- lib/lhc/formats/json.rb
- lib/lhc/request.rb
- lib/lhc/response/data/base.rb
- lib/lhc/version.rb
- spec/basic_methods/post_spec.rb
- spec/basic_methods/put_spec.rb
- spec/basic_methods/request_without_rails_spec.rb
- spec/request/url_patterns_spec.rb
MAJOR (not backwards compatible)
Even though JSON already has been our default format when performing HTTP requests ([see here](https://github.com/local-ch/lhc/blob/master/lib/lhc/request.rb#L22)), we were still obliged to translate the body option to json, before passed to LHC, when performing requests having an HTTP body.
```ruby
LHC.post('http://datastore', body: { name: 'Steve' }.to_json)
```
This also led to inelegant implementations, assuming or hard-code checking for "application/json" or a json-like string in the body  – e.g. when compiling the url ([see here](https://github.com/local-ch/lhc/blob/master/lib/lhc/request.rb#L103)) – and even though we have the http message "format" abstracted in LHC ([see here](https://github.com/local-ch/lhc/blob/master/lib/lhc/formats/json.rb)) …
> Simplify making JSON requests

- lib/lhc/formats/json.rb
- lib/lhc/version.rb
- spec/basic_methods/get_spec.rb
- spec/formats/json_spec.rb
- spec/response/data_accessor_spec.rb
Minor (backwards compatible)
A lot of APIs actually require a explicit charset to be defined together with the content type (e.g. Slack).
LHC was not setting the charset:
```
Content-Type: application/json
Accept: application/json
```
LHC adds charset
```
Content-Type: application/json; charset=utf-8
Accept: application/json; charset=utf-8
```
> Adding charset when setting media type headeres

- lib/lhc/interceptors/zipkin.rb
- lib/lhc/version.rb
- spec/interceptors/zipkin/distributed_tracing_spec.rb
- spec/support/zipkin_mock.rb
after letting the implementation run in the real-world. @golonzovsky and I have found an issue with spans that were not being added to parent. 
turns out my implementation created unecessary spans that lead to that behavior.
this PR ensures:
- B3 headers are always sent even if `sampled?` is `false`
- however a span is only created if `sampled?` is `true`
> Fix zipkin 8.1.0

- lib/lhc/interceptors/zipkin.rb
- lib/lhc/version.rb
- spec/interceptors/zipkin/distributed_tracing_spec.rb
- spec/support/zipkin_mock.rb
after letting the implementation run in the real-world. @golonzovsky and I have found an issue with spans that were not being added to parent. 
turns out my implementation created unecessary spans that lead to that behavior.
this PR ensures:
- B3 headers are always sent even if `sampled?` is `false`
- however a span is only created if `sampled?` is `true`
> Fix zipkin 9.1.0

- README.md
- docs/interceptors.md
This PR links documentation to the directory containing all core interceptor documentations, rather that listing them in various places. Should improve maintainability of the docs.
> Reference list/dir of core interceptors rather than listing every single one

- docs/interceptors/logging.md
- lib/lhc.rb
- lib/lhc/interceptors/logging.rb
- spec/interceptors/logging/main_spec.rb
The logging interceptor logs all requests done with LHC to the Rails logs.
```ruby
LHC.config.interceptors = [LHC::Logging]
LHC::Logging.logger = Rails.logger  
```
The logging Interceptor logs basic information about the request and the response:
```ruby
LHC.get('http://local.ch')
```
You can configure the logger beeing used by the logging interceptor:
```ruby
LHC::Logging.logger = Another::Logger
```
> Logging Interceptor

- docs/interceptors/monitoring.md
- lib/lhc/interceptors/monitoring.rb
- lib/lhc/version.rb
- spec/interceptors/monitoring/main_spec.rb
The monitoring interceptor was using `Rails.env` to determine the environment it is reporting for to Statsd.
In deployed environments like Kubernetes, where we use Rails.env production for dev/beta/production, but use ENV[`DEPLOYMENT_TYPE`] to define the final environment, the monitoring interceptor needs to be configurable in regards of the `env` it uses for reporting.
> Configurable monitoring ENV

- lib/lhc/formats/json.rb
- lib/lhc/request.rb
- lib/lhc/version.rb
- spec/request/body_spec.rb
_PATCH_
LHC was trying to encode a given body in it's default format (JSON), even though it might have been already decoded.
This PR patches the previous behaviour. When a body, using the JSON format, is already encoded (a string), it does not encode it (again).
> Do not encode json formatted body twice

- lib/lhc/concerns/lhc/request/user_agent_concern.rb
- lib/lhc/version.rb
In real life, LHC was raising an exception when it was trying to access the VERSION constant for the `User-Agent` header. Unfortunately that was not reproducible with tests.
> Fix require `lhc/version`

- lib/lhc/request.rb
- lib/lhc/version.rb
- spec/request/url_patterns_spec.rb
_Targeting 10.0.2_
_Backport as 9.4.4_
In https://github.com/local-ch/lhc/releases/tag/v9.4.3 I introduced the assumption, that the passed body is always a Hash.
Turns out LHS passes LHS::Data and LHS::Record down to LHC as bodies.
This PR fixes the compatibility to LHS and allows custom structures to be passed, as long as they respond to `as_json`.
> Do not assume hashes when trying to get data from body

- lib/lhc.rb
- lib/lhc/format.rb
- lib/lhc/formats/json.rb
- lib/lhc/formats/multipart.rb
- lib/lhc/formats/plain.rb
- lib/lhc/request.rb
- lib/lhc/version.rb
- spec/basic_methods/request_without_rails_spec.rb
- spec/formats/json_spec.rb
_PATCH_
Will back port to 10.0.1, too.
This PR introduces exceptions when LHC is asked to set the "Content-Type" or "Accept" (in case of json), when the request is already formatted!
> Raise exception if passing headers to formatted requests

- README.md
- lib/lhc/format.rb
- lib/lhc/version.rb
- spec/formats/json_spec.rb
Would it make sense to be clearer in the error messages? My proposal is easier to _CTRL+F_.
> Increase verbosity of format errors

- lhc.gemspec
- lib/lhc/formats/json.rb
- lib/lhc/version.rb
- spec/formats/json_spec.rb
- spec/response/data_accessor_spec.rb
json:api is a content-type that some APIs support. It is documented in
great detail here: https://jsonapi.org/
LHC/LHS can handle both content types and can safely state so in the accept
header.
Instead of appending the charset to the accept header, use the dedicated
Accept-Charset header which takes precedence over the appended charset part
in the Accept header.
> Update Charset and Content-Type Headers

- lib/lhc/request.rb
- lib/lhc/version.rb
- spec/request/ignore_errors_spec.rb
_PATCH_
Fixes the cases where ignore errors was called with `[nil]` `nil` from LHS.
Does not fail now, just ignores those params.
> Fix ignored errors with nil

- lib/lhc/interceptors/zipkin.rb
- lib/lhc/version.rb
We get the following warnings a lot (unnecessarily)
```
[WARNING] Zipkin interceptor is enabled but dependencies are not found. See: https://github.com/local-ch/lhc#zipkin
```
This PR decouples `tracing?` (if tracing is happening) from `dependencies?` (which clearly just checks for dependencies.
So in your tests it would still complain if Zipkin has wrong dependencies (which might make your app crash when deployed), but it's not flooding you with warnings any longer, just because there is no current trace!
> Avoid zipkin warnings in test and dev

- README.md
- friday.yml
- lib/lhc.rb
- lib/lhc/interceptors/throttle.rb
- lib/lhc/version.rb
- spec/interceptors/throttle/main_spec.rb
This PR introduces the throttle interceptor.
The throttle interceptor allows you to raise an exception if a predefined quota of an provider request limit is reached in advance.
```ruby
LHC.configure do |c|
c.interceptors = [LHC::Throttle]
end
```
```ruby
options = { 
throttle: {
track: true, # enables tracking of current limit/remaining requests of rate-limiting
break: '80%', # quota in percent after which errors are raised
provider: 'local.ch', # name of the provider under which throttling tracking is aggregated,
limit: { header: 'Rate-Limit-Limit' }, # either a hard-coded integer, or a hash pointing at the response header containing the limit value
remaining: { header: 'Rate-Limit-Remaining' }, # a hash pointing at the response header containing the current amount of remaining requests …
```
> Throttle interceptor

- lib/lhc/interceptors/throttle.rb
- lib/lhc/version.rb
- spec/interceptors/throttle/main_spec.rb
Was throwing exception when response had no headers set. Now does not raise any more.
> Fix accessing none existing headers

- lib/lhc/interceptors/throttle.rb
- spec/interceptors/throttle/main_spec.rb
This PR fixes the case where tracked remaining was nil, and throttling break threw an exception.
> Fix case where tacked reamining is nil

- README.md
- lhc.gemspec
- lib/lhc/interceptors/throttle.rb
- lib/lhc/version.rb
- spec/interceptors/throttle/main_spec.rb
- spec/spec_helper.rb
Having throttling expire is kind of necessary, that's also why this PR is patching the version.
Otherwise, as soon as the throttling interceptor hits the break, he will never get out of the break state again, as no further request would be allowed, which would update the current quota.
> Throttling expires

- .rubocop.yml
- README.md
- lib/lhc/rspec.rb
- lib/lhc/test/cache_helper.rb
- lib/lhc/version.rb
- spec/interceptors/throttle/reset_track_spec.rb
This PR introduces a more generic test helper to require within your application when using LHC.
It also introduces a test to actually test Throttling track to be reset between tests.
> More generic rspec helper

- README.md
- lib/lhc/interceptors/retry.rb
- lib/lhc/version.rb
- spec/interceptors/retry/main_spec.rb
_PATCH_
This PR makes the retry interceptor consider to not retry a request if the error (response) was explicitly ignored. (Which was expected to work that way.)
If you do not want to retry based on certain response codes, use retry in combination with explicit `ignore_errors`:
```ruby
LHC.get('http://local.ch', ignore_errors: [LHC::NotFound], retry: { max: 1 })
```
Or if you use `LHC::Retry.all`:
```ruby
LHC.get('http://local.ch', ignore_errors: [LHC::NotFound])
```
> Consider ignore_errors when retrying requests

- lib/core_ext/hash/deep_transform_values.rb
- lib/lhc.rb
- lib/lhc/concerns/lhc/fix_invalid_encoding_concern.rb
- lib/lhc/error.rb
- lib/lhc/interceptors/rollbar.rb
- lib/lhc/version.rb
- spec/core_ext/hash/deep_transform_values_spec.rb
- spec/interceptors/rollbar/invalid_encoding_spec.rb
- spec/interceptors/rollbar/main_spec.rb
we have an issue on the `ratings` app where the rollbar notification results in an `Encoding::UndefinedConversionError` (https://rollbar.com/local.ch/ratings/items/10/)
we assume this masks the underlying cause of the initial rollbar warning.
this is an attempt of recovering in such a case, by sanitizing the data sent to rollbar.
- the rspecs are a bit awkward. I did my best to make them concise
- if someone knows a better way of setting up a spy that first throws an exception and the second time not, im all ears!
> Rollbar interceptor error handling

- lib/lhc/interceptors/prometheus.rb
- lib/lhc/version.rb
The setting of the registering is not atomic, so it could happen that on start up, the `registered` flag is not yet set when a second thread initialises the Prometheus interceptor again. Simply adding a rescue for this case prevents an exception.
This should be idiomatic anyway.
> Mitigate Race Condition when initialising Prometheus

- lib/lhc/concerns/lhc/basic_methods_concern.rb
- lib/lhc/version.rb
- spec/request/parallel_requests_spec.rb
This is a big one.
For those of you that know, but some of our applications are constantly suffering from `Status 0 (timeout)` responses.
Especially in AMA where there was nothing else left to do, but recycling the pods, in order to get the application stable again.
LHC uses `Typhoeus::Hydra` to parallelize requests. https://github.com/typhoeus/typhoeus/blob/master/lib/typhoeus/hydra.rb#L67
LHC used the memorized instance of Hydra.
When one single request failed during the parallelization, it left the memoized hydra in it's current state. Because every single request in the parallelization calls back, and when one of them raises an error through LHC the others will not continue, and worse, will leave the memoized hydra in it's current state. …
> Do not use Typhoeus::Hydra memoization

- lib/lhc/concerns/lhc/formats_concern.rb
- lib/lhc/formats.rb
- lib/lhc/formats/form.rb
- lib/lhc/version.rb
- spec/formats/form_spec.rb
- spec/formats/multipart_spec.rb
This PR adds the `form` format, which allows to make easy `application/x-www-form-urlencoded` requests with an urlencoded body.
Needed for sf token issuing.
> Form format

- lib/lhc/interceptors/auth.rb
- lib/lhc/version.rb
- spec/interceptors/auth/reauthentication_spec.rb
When this feature was introduced, there was only 1 bearer token format, the one from auth.local.ch. 
Now with Salesforce we have a second bearer token issuer, and this PR weakens the criterias under which a `reauthenticate?` is performed to refresh client tokens.
> Token format to evaluate reauthenticate? was too strict

- lib/lhc/error.rb
- lib/lhc/request.rb
- lib/lhc/version.rb
- spec/request/ignore_errors_spec.rb
We discovered a bug in LHS where including resources that can not be found wouldn't work as expected.
This is a first improvement (minor) to solve the overall issue.
> allow single keys to be passed as ignored_errors

- lib/lhc/interceptors/auth.rb
- lib/lhc/version.rb
- spec/interceptors/auth/no_instance_var_for_options_spec.rb
https://github.com/local-ch/lhc/releases/tag/v12.1.0 introduced a bug. 
Because the auth interceptors uses instance variables for `auth_options` once it has been initalized with the `before_raw_request` hook (as used by body  auth) other interceptors can not pass auth options anymore even at a later hook (`before_request`).
This PR removes the instance variable usage and lets auth interceptor always access the original auth option hash. So that other interceptor can prepare those options (like LHS auto auth interceptor).
> No instance variable for auth options

- lib/lhc/response/data.rb
- lib/lhc/response/data/base.rb
- lib/lhc/version.rb
- spec/response/data_spec.rb
When error response bodies where containing a "response" key, lhc's internal Data::Base was running into a `SystemStackError: stack level too deep` error (e.g. https://rollbar.com/local.ch/opm/items/83972/occurrences/133328495053/).
This PR fixes that issue.
> Fix nested base data response accessors

- README.md
- lib/lhc/interceptors/throttle.rb
- lib/lhc/version.rb
- spec/interceptors/throttle/main_spec.rb
https://jira.localsearch.ch/browse/pro-1313
Allow all values that deal with header information to be procs.
> PRO-1313 Allow Procs For All Configuration Values

- README.md
- lib/lhc/concerns/lhc/request/user_agent_concern.rb
- lib/lhc/error.rb
- lib/lhc/interceptor.rb
- lib/lhc/interceptors/auth.rb
- lib/lhc/interceptors/caching.rb
- lib/lhc/interceptors/monitoring.rb
- lib/lhc/request.rb
- lib/lhc/version.rb
- spec/error/to_s_spec.rb
- spec/interceptors/after_response_spec.rb
- spec/interceptors/caching/main_spec.rb
- spec/interceptors/caching/multilevel_cache_spec.rb
- spec/interceptors/monitoring/caching_spec.rb
- spec/interceptors/response_competition_spec.rb
- spec/interceptors/return_response_spec.rb
This Introduces monitoring for caching.
It extends the monitoring interceptor to record `miss` or `hit` in order to monitor http caching.
Also:
- Fixes some `module_parent_name` calls to improve support of active support 5 and 6 and to get rid of some warnings
- Fixes a bug where interceptors `after_response` was not called, if a response was served from cache
> Monitor Caching

- lib/lhc/version.rb
Release with fixed warning `URI.escape is obsolete` mentioned here: https://github.com/local-ch/lhc/issues/193
> Release 13.2.0.

- lib/lhc/version.rb
In the last release we force the consumers of this gem to use at least ruby version 2.7.
This would have needed to be a major instead of a minor release.
With this PR we are going to create a major release. Afterwards i will yank the wrong version from ruby gems and delete the release from Github so in the end the major release is left.
Wrong release:
https://github.com/local-ch/lhc/releases/tag/v13.3.0
> Correct release version of latest release

- lib/lhc/request.rb
- lib/lhc/scrubbers/headers_scrubber.rb
- lib/lhc/version.rb
- spec/request/scrubbed_headers_spec.rb
When the main app does a request either with bearer of or basic auth and the LHC config does scrub the whole header `config.scrubs[:headers] << 'Authorization' ` then we run into `FrozenError (can't modify frozen String: "[FILTERED]")`.
The problem is that we want to `.gsub!` a string which was already filtered before and that then causes the error.
This PR fixes that and makes sure to scrub only auth headers which are not already scrubbed.
> Fix `FrozenError (can't modify frozen String: "[FILTERED]")`

- lib/lhc/scrubbers/cache_scrubber.rb
- lib/lhc/version.rb
- spec/request/scrubbed_options_spec.rb
When a request url did include a parmater which did not match any provided parameter to be scrubbed, then the app ran into:
```
expected LHC::NotFound, got #<NoMethodError: undefined method `[]' for nil:NilClass>
```
This PR fixes that.
> Fix issue with parameter scrubbing

- .rubocop.yml
- lhc.gemspec
- lib/lhc/interceptors/auth.rb
- lib/lhc/version.rb
Since rails 7 `sprockets-rails` gem is an optional dependency. As our dummy app is using it, i added this gem to the list of development dependencies.
I also created the separate issue about the usage of `OpenStruct`: https://github.com/local-ch/lhc/issues/206
> Add sprockets-rails gem as a dev dependency

- lib/lhc/interceptors/auth.rb
- lib/lhc/interceptors/rollbar.rb
- lib/lhc/version.rb
- spec/interceptors/auth/reauthentication_spec.rb
- spec/interceptors/rollbar/main_spec.rb
https://jira.localsearch.ch/browse/LCL-2447
Starting from the release 15.0.0 re-authentication mechanism doesn't work properly for the endpoints without "auth" options. This PR fixes it.
> [LCL-2447] - Fix re-authentication for the endpoints without auth options.

- lhc.gemspec
- lib/lhc/interceptors/rollbar.rb
- lib/lhc/version.rb
- spec/error/to_s_spec.rb
- spec/interceptors/rollbar/main_spec.rb
_MINOR_
Stop reporting to Rollbar if errors are explicitly ignored.
> Do not report to rollbar ignored errors

- lib/lhc/scrubbers/headers_scrubber.rb
- lib/lhc/version.rb
- spec/request/scrubbed_headers_spec.rb
It seems that we have cases when there is a bearer proc but no bearer_token. So this PR is covering that case.
> Cover the case when there is a beaerer proc but no bearer token
